services:
  # A Docker web service
  - type: web
    name: traffic-accidents-shiny
    env: docker
    dockerfilePath: ./SETUP/dockerfile
    dockerContext: ./SETUP
    plan: free
    repo: https://github.com/darrendariustan/r-shiny-traffic-accidents
    branch: master
    healthCheckPath: /
    envVars:
      - key: R_SHINY_PORT
        value: 3838
    buildFilter:
      paths:
        - SRC/**
        - DATA/**
        - SETUP/**
    mounts:
      - source: ./SRC
        destination: /src
        type: custom
      - source: ./DATA
        destination: /data
        type: custom
