services:
  # A Docker web service
  - type: web
    name: traffic-accidents-shiny
    runtime: docker
    dockerfilePath: ./SETUP/dockerfile
    dockerContext: .
    plan: free
    repo: https://github.com/darrendariustan/r-shiny-traffic-accidents
    branch: main
    healthCheckPath: /
    envVars:
      - key: R_SHINY_PORT
        value: 3838
    buildFilter:
      paths:
        - SRC/**
        - DATA/**
        - SETUP/**
